include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
#    missing_return: info
    todo: ignore


linter:
  rules:
    - camel_case_types

