name: expandable_tree_menu
description: Tree of menu-nodes that can be expanded/collapsed to review more menu nodes, built from a recursive list of nodes.
version: 0.1.0-dev.5
homepage: https://github.com/Tahaan/expandable_tree_menu
repository: https://github.com/Tahaan/expandable_tree_menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: